#!/bin/bash

# the orignal script location: http://www.raspberryconnect.com/images/autohotspotN/autohotspotN1:w
# relative artical: http://www.raspberryconnect.com/network/item/330-raspberry-pi-auto-wifi-hotspot-switch-internet

#version 0.89-N/HS-I

#You may share this script but a reference to RaspberryConnect.com must be included in copies or derivatives of this script. 

#Wifi & Hotspot with Internet
#A script to switch between a wifi network and an Internet routed Hotspot
#Raspberry Pi with a network port required for Internet in hotspot mode.
#Works at startup or with a seperate timer or manually without a reboot
#Other setup required find out more at
#http://www.raspberryconnect.com


#These four lines capture the wifi networks the RPi is setup to use
#IFSdef=$IFS
#wpassid=$(awk '/ssid="/{ print $0 }' /etc/wpa_supplicant/wpa_supplicant.conf | awk -F'ssid=' '{ print $2 }' ORS=',' | sed 's/\"/''/g' | sed 's/,$//')
#IFS=","
#ssids=($wpassid)
#IFS=$IFSdef #reset back to defaults

#Note:If you only want to check for certain SSIDs
#Remove the # in in front of ssids=('mySSID1'.... below and put a # infront of all four lines above
# separated by a space, eg ('mySSID1' 'mySSID2')
#ssids=('mySSID1' 'mySSID2' 'mySSID3')

IF_NAME='wlan0'
IF_ADDR='10.0.100.1/24 broadcast +'

activate_ad_hoc()
{
    ip link set dev $IF_NAME down
    ip addr add $IF_ADDR dev $IF_NAME
    ip link set dev $IF_NAME up
    iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
    iptables -A FORWARD -i eth0 -o $IF_NAME -m state --state RELATED,ESTABLISHED -j ACCEPT
    iptables -A FORWARD -i $IF_NAME -o eth0 -j ACCEPT
    systemctl start dnsmasq
    systemctl start hostapd
    echo 1 > /proc/sys/net/ipv4/ip_forward
}

deactivate_ad_hoc()
{
    echo "Shutting Down Hotspot"
    ip link set dev $IF_NAME down
    systemctl stop hostapd
    systemctl stop dnsmasq
    iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
    iptables -D FORWARD -i eth0 -o $IF_NAME -m state --state RELATED,ESTABLISHED -j ACCEPT
    iptables -D FORWARD -i $IF_NAME -o eth0 -j ACCEPT
    echo 0 > /proc/sys/net/ipv4/ip_forward
    ip addr flush dev $IF_NAME
    ip link set dev $IF_NAME up
}

wifi_activated()
{
    wpa_cli status | grep 'ip_address' >/dev/null 2>&1
}

activate_wifi()
{
    wifi_activated || {
        wpa_supplicant -B -i $IF_NAME -c /etc/wpa_supplicant/wpa_supplicant.conf >/dev/null 2>&1
    }
}

deactivate_wifi()
{
    wpa_cli terminate >/dev/null 2>&1
}

scan_ssids()
{
    iw dev $IF_NAME scan ap-force | sed -n 's/[[:space:]]*SSID:[[:space:]]*\(.*\)/\1/p'
}

ssids_configured()
{
    sed -n 's/.*ssid="\(.*\)"/\1/p' /etc/wpa_supplicant/wpa_supplicant.conf
}


#Enter the Routers Mac Addresses for hidden SSIDs, seperated by spaces ie 
#( '11:22:33:44:55:66' 'aa:bb:cc:dd:ee:ff' ) 
ssids_online="$(scan_ssids)"
mac=()
ssidsmac=("${ssids[@]}" "${mac[@]}") #combines ssid and MAC for checking


#Check to see what SSID's and MAC addresses are in range
ssidChk=('NoSSid')
for ssid in "${ssidsmac[@]}"
do
     if { echo $ssids_scanned | grep "$ssid"; } >/dev/null 2>&1
     then
              ssidChk=$ssid
              break
       else
              ssidChk='NoSSid'
     fi
done

#Create Hotspot or connect to valid wifi networks
if [ $ssidChk != "NoSSid" ] 
then
       echo 'Using SSID:' $ssidChk
       echo 0 > /proc/sys/net/ipv4/ip_forward #deactivate ip forwarding
       if systemctl status hostapd | grep "(running)" >/dev/null 2>&1
       then #hotspot running and ssid in range
              deactivate_ad_hoc
              echo "Hotspot Deactivated, Bringing Wifi Up"
              activate_wifi
       elif { wpa_cli status | grep 'ip_address'; } >/dev/null 2>&1
       then #Already connected
              echo "Wifi already connected to a network"
       else #ssid exists and no hotspot running connect to wifi network
              echo "Connecting to the WiFi Network"
              activate_wifi
       fi
else #ssid or MAC address not in range
       if systemctl status hostapd | grep "(running)" >/dev/null 2>&1
       then
              echo "Hostspot already active"
       elif { wpa_cli status | grep '$IF_NAME'; } >/dev/null 2>&1
       then
              echo "Cleaning wifi files and Activating Hotspot"
              wpa_cli terminate >/dev/null 2>&1
              ip addr flush $IF_NAME
              ip link set dev $IF_NAME down
              rm -r /var/run/wpa_supplicant >/dev/null 2>&1
              activate_ad_hoc
       else #"No SSID, activating Hotspot"
              activate_ad_hoc
       fi
fi

